### ISSUE TITLE
npm package doesn't contain pre-built code

### ISSUE THREAD

**Issue by Syynth** [ConciergeAuctions/relay-cache-manager#14]
It appears version 0.2.0 was published without the code being compiled. `npm i relay-cache-manager` yields a package with a `src` directory but no `lib` directory.

**Comment by Aweary** [comment]
Thanks @Syynth, our `prepublish` script should have automatically built the package, so I'll look into why it didn't.

**Comment by Aweary** [comment]
@Syynth not sure why `0.2.0` didn't work, but I published `0.2.1` after testing our build script and it looks like `lib` is available in the install now.
